# Site settings
title: Another Blog
url: "https://lucaslopescontrera.github.io/"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: 
#timezone: Asia/Chongqing
description: >
  One or more sentences introducing this blog.

# Your information
email: lopcont@gmail.com
author: Lucas Contrera
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: Meu Nome é Lucas.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:"
  GitHub: "https://github.com/LucasLopesContrera/LucasLopesContrera.github.io.git"
  # You can add more profile links above, or edit _includes/sidebar.html 


#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
